name : Hello World Workflow

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:



jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: hello world
        run: echo "Hello world from my side"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: goodbye world
        run: echo "Goodbye world from my side"
        shell: bash
